name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Override the default permissions granted to the GITHUB_TOKEN
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: version logic
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\/v/}
            echo "Tag build detected: ${VERSION}"
          else
            VERSION="0.0.0"
            echo "Trunk build detected: ${VERSION}"
          fi

          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"


      - name: Build and test helm chart
        run: ./build/build-helm.sh argoApps
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Push tagged helm chart to repo
        if: ${{ steps.version.outputs.VERSION != '0.0.0' }}
        run: ./build/push-repo.sh
        env:
          KIT_GITHUB_ACCESS: ${{ secrets.KIT_GITHUB_ACCESS }}
